### ISSUE TITLE
[FEATURE] Folders filters by glob

### ISSUE THREAD

**Issue by ghost** [canton7/backer_upper#1]
It might be very useful to have the ability to exclude folders through a glob filter, just like for files.
For example, this feature can be useful if you want to exclude all `.git` folders from a complex backup.

**Comment by canton7** [comment]
Thanks for your suggestion. Unfortunately I wrote this piece of software 5 years ago for personal use, and I'm not interested in developing it further. Contributions welcome however.

**Comment by ghost** [comment]
Ok, I try to develop it.
