### ISSUE TITLE
Scheduled time not show if it set AM or PM hour

### ISSUE THREAD

**Issue by ghost** [canton7/backer_upper#2]
Scheduled time settings appears as 0-12 format but it not show AM/PM.

![2017-10-06_li](https://user-images.githubusercontent.com/11737918/31256568-9e0df4fc-aa33-11e7-8851-830d2ecc1664.jpg)

**Comment by canton7** [comment]
![image](https://user-images.githubusercontent.com/568104/31267568-87f41858-aa70-11e7-9cda-82235cab607c.png)

Weird, must be a result of your locale settings. Fixes welcome.

**Comment by ghost** [comment]
Ok, I try to fix it.
